host: khemenu.thoth-station.ninja
tls_verify: true
requirements_format: pipenv
overlays_dir: overlays

runtime_environments:
  - name: ps-cv-ocr
    operating_system:
      name: ubi
      version: "8"
    python_version: "3.8"
    recommendation_type: latest

  - name: ps-cv-pytorch
    operating_system:
      name: ubi
      version: "8"
    python_version: "3.8"
    recommendation_type: latest

  - name: ps-cv-tensorflow
    operating_system:
      name: ubi
      version: "8"
    python_version: "3.8"
    recommendation_type: latest

managers:
  - name: update
    configuration:
      labels: [bot]
  - name: info
  - name: version
    configuration:
      assignees:
        - sesheta
      labels: [bot]
      changelog_file: true
  - name: thoth-advise
    configuration:
      labels: [bot]
